### PR TITLE
#86 Crash on during evaluation

### LINKED ISSUE #86: Crash on during evaluation
Reversatile version 1.4.14 

When pasting a (finished) game sequence, fast backwards to first move and eveluating per next move basis, Reversatile on android crashes with certain move sequences. I can predictably replicate this bug on sequence:
c4c3d3c5b3f4b5b4a5a3c6d6f3c2d1e6d2b6g4e2e3f2e1f1g1f5g6a6a7a2c7d7d8e7e8f7f6f8g8g5h4b1b2a1c1a4a8b7b8c8h8g7h7h6h5h3h1g2
The crash occurs between c5 and b3.
I've noticed this behaviour before with different games and at different move numbers but never documented them.

### PR DESCRIPTION
**Pull request by oers**

### CODE REVIEW

File: project/src/main/jni/droidzebra-jni.c [hunk 1]
```diff
@@ -1124,7 +1123,6 @@ void _droidzebra_throw_engine_error(JNIEnv* env, const char* msg)
 
 void _droidzebra_undo_stack_push(int val)
 {
-	assert(s_undo_stack_pointer<64);
```
Comment (panstromek) [inline project/src/main/jni/droidzebra-jni.c:1127]: `s_undo_stack` size is 64, so if this `assert` is triggered here, it's definitely a bug. If we remove it, it will just silently overflow the buffer, there's no logic to grow that buffer here.

Comment (oers) [reply project/src/main/jni/droidzebra-jni.c:1127]: I think, that the stack size is too small, without the asserts everything works perfectly. But I am just trying to find out how often this is increased.

Comment (panstromek) [reply project/src/main/jni/droidzebra-jni.c:1127]: > without the asserts everything works perfectly

This can be very misleading - it just means that the value is written somewhere in the memory and the program has no problems writing to it - that doesn't mean that the memory is valid. A little change in the code can move the array somewhere else in memory and cause a bug, either a crash if it's on page boundary, or something more problematic by overriding unrelated data.

I think it makes sense to increase the stack size, but I'd definitely not remove the assert, because it guards a real bug.

Comment (oers) [reply project/src/main/jni/droidzebra-jni.c:1127]: Stack size is now 120
There are 60 White and 60 Black moves maximum (each move can be a pass)

Comment (panstromek) [reply project/src/main/jni/droidzebra-jni.c:1127]: To clarify - it's possible that the assert went away only because you've also added the `undoall` text and that changed the layout of the code, it may not even be related to that assert.

That would also make sense, because asserts are usually completely removed in production builds. I'm not sure if we do that here, you can test this by adding `assert(false)` somewhere and run a production build.

Comment (oers) [reply project/src/main/jni/droidzebra-jni.c:1127]: I deleted the assert. I reintrocuded it. 
64 worked until 4 Passes were made. After that the assert always failed.
I think the asserts were disabled in production or before some c refactoring. And the Application crashed when doing redo. In my current version it crashed at undo at the assert

Comment (panstromek) [reply project/src/main/jni/droidzebra-jni.c:1127]: > Stack size is now 120 There are 60 White and 60 Black moves maximum (each move can be a pass)

That sounds plausible, good catch. Does the game from the bug report have a lot of passes?

Comment (oers) [reply project/src/main/jni/droidzebra-jni.c:1127]: like 7 or 8, Lots of passes.
